### ISSUE TITLE
Statamic v3.4

### ISSUE THREAD

**Issue by jimblue** [HandmadeWeb/statamic-cloudflare#2]
Statamic v3.4 has been released. 🎉 
Can you please bump composer.json and create a new release ?
Thank you 🙏🏼

**Comment by jimblue** [comment]
Hi @michaelr0,
I've just create a PR to fix this issue.
Can you please merge it and create the release?
Thank you 🙏🏼

**Comment by michaelr0** [comment]
Thanks @jimblue 

This will be tagged as 1.0.7 :)

**Comment by jimblue** [comment]
Awesome 🎉
