### ISSUE TITLE
Support Statamic v4

### ISSUE THREAD

**Issue by jimblue** [HandmadeWeb/statamic-cloudflare#4]
Thank you so much :) 🙏🏼

**Comment by jimblue** [comment]
Hi @michaelr0,
I've just create #5 to fix this issue.
Can you please merge it and create the release?
Thank you 🙏🏼

**Comment by michaelr0** [comment]
Thanks @jimblue 

This has been tagged as [2.0.0](https://github.com/HandmadeWeb/statamic-cloudflare/releases/tag/2.0.0)

**Comment by jimblue** [comment]
Great, thank you for the release! 🎉
