### ISSUE TITLE
Support for Statamic 5+

### ISSUE THREAD

**Issue by brew-cristian** [HandmadeWeb/statamic-cloudflare#8]
### Support for Statamic 5+

Hi,

I am currently using Statamic 5 and would like to use the `handmadeweb/statamic-cloudflare` package with it. However, it seems that the package currently only supports up to Statamic 4.

Could you please add support for Statamic 5+?

Thank you for your hard work on this package!

Best regards,
Cristian.

**Comment by miteyema** [comment]
I've already made a PR https://github.com/HandmadeWeb/statamic-cloudflare/pull/7.

**Comment by RobReckham** [comment]
+1

**Comment by lokmanm** [comment]
+1

**Comment by bland-industries** [comment]
... Hello? is the PR going to be merged? Does anyone have an update?

**Comment by michaelr0** [comment]
This is being merged now, Thanks @miteyema
